const songs = [
  { artist: "DeBarge", title: "Rhythm Of The Night", year: 1985 },
  { artist: "blink-182", title: "All The Small Things", year: 1999 },
  { artist: "kent", title: "Dom andra", year: 2002 },
  { artist: "Arvingarna", title: "Eloise", year: 1993 },
  { artist: "Crazy Town", title: "Butterfly", year: 1999 },
  { artist: "Twisted Sister", title: "We're Not Gonna Take It", year: 1984 },
  { artist: "Brainpool", title: "Bandstarter", year: 1995 },
  { artist: "Haddaway", title: "What Is Love - 7\" Mix", year: 1993 },
  { artist: "Diana Ross", title: "I'm Coming Out", year: 1980 },
  { artist: "Peter Cetera", title: "Glory of Love", year: 1986 },
  { artist: "Tommy Nilsson", title: "Öppna din dörr", year: 1995 },
  { artist: "Raymond & Maria", title: "Ingen vill veta var du köpt din tröja", year: 2004 },
  { artist: "John Farnham", title: "You're the Voice", year: 1986 },
  { artist: "The Chainsmokers;Coldplay", title: "Something Just Like This", year: 2017 },
  { artist: "Zara Larsson;MNEK", title: "Never Forget You", year: 2017 },
  { artist: "Miriam Bryant;Victor Leksell", title: "tystnar i luren", year: 2021 },
  { artist: "Jonathan Johansson", title: "Rosa himmel", year: 2016 },
  { artist: "Miss Li", title: "Komplicerad", year: 2021 },
  { artist: "Sten & Stanley", title: "Jag vill vara din, Margareta", year: 1976 },
  { artist: "Sweetbox", title: "Everything's Gonna Be Alright", year: 1998 },
  { artist: "Seal", title: "Kiss from a Rose", year: 1994 },
  { artist: "Thomas Rusiak;Teddybears", title: "Hiphopper (feat. Teddybears Sthlm)", year: 2016 },
  { artist: "Swedish House Mafia;John Martin", title: "Don't You Worry Child - Radio Edit", year: 2012 },
  { artist: "Wilson Pickett", title: "In the Midnight Hour", year: 1965 },
  { artist: "Fronda", title: "Rullar fram", year: 2007 },
  { artist: "Victor Leksell", title: "Svag", year: 2020 },
  { artist: "Peggy Lee", title: "Fever", year: 1988 },
  { artist: "Tommy Körberg", title: "Stad i ljus", year: 1995 },
  { artist: "Ted Gärdestad", title: "Jag ska fånga en ängel", year: 1973 },
  { artist: "Christian Walz", title: "Wonderchild", year: 2004 },
  { artist: "Antique", title: "Opa Opa", year: 1999 },
  { artist: "Bo Kaspers Orkester", title: "I samma bil", year: 2006 },
  { artist: "BlackJack", title: "Inget stoppar oss nu", year: 1990 },
  { artist: "Gyllene Tider", title: "När vi två blir en", year: 1981 },
  { artist: "Hasse Andersson", title: "Änglahund", year: 1982 },
  { artist: "Foreigner", title: "I Want to Know What Love Is - 1999 Remaster", year: 1984 },
  { artist: "Dag Vag", title: "Popitop", year: 1988 },
  { artist: "PSY", title: "Gangnam Style (강남스타일)", year: 2012 },
  { artist: "Imperiet", title: "Du ska va president", year: 1990 },
  { artist: "Alina Devecerski", title: "Flytta på dej", year: 2012 },
  { artist: "Lisa Nilsson", title: "Himlen runt hörnet", year: 1992 },
  { artist: "E-Type", title: "This Is The Way - Radio Edit", year: 1994 },
  { artist: "MGMT", title: "Kids", year: 2007 },
  { artist: "Myra Granberg", title: "Lose my mind", year: 2021 },
  { artist: "AronChupa;Little Sis Nora", title: "I'm an Albatraoz", year: 2014 },
  { artist: "Håkan Hellström", title: "Det kommer aldrig va över för mig", year: 2013 },
  { artist: "Albin Lee Meldau", title: "Josefin", year: 2021 },
  { artist: "Veronica Maggio;Håkan Hellström", title: "Hela huset", year: 2013 },
  { artist: "Jakob Karlberg", title: "Fan va bra", year: 2015 },
  { artist: "Hov1;Einár", title: "Gamora", year: 2021 },
  { artist: "Björn Skifs", title: "Michelangelo (Men så svara då!)", year: 1975 },
  { artist: "Racey", title: "Kitty", year: 2009 },
  { artist: "Mary Mary", title: "Shackles (Praise You)", year: 2000 },
  { artist: "Mando Diao", title: "Dance With Somebody - Radio Version", year: 2009 },
  { artist: "Yolanda Be Cool;DCup", title: "We No Speak Americano (Edit)", year: 2020 },
  { artist: "Outlandish", title: "Aicha", year: 2003 },
  { artist: "Christer Björkman", title: "I morgon är en annan dag", year: 1992 },
  { artist: "Petter;Eye N'I", title: "Såklart! (feat. Eye N'I)", year: 1999 },
  { artist: "Kenny Rogers", title: "The Gambler", year: 1978 },
  { artist: "Galenskaparna & After Shave", title: "Gótt å leva", year: 1994 },
  { artist: "Basshunter", title: "Boten Anna - Radio edit", year: 2006 },
  { artist: "Monica Zetterlund", title: "Sakta vi gå genom stan", year: 1962 },
  { artist: "The Ting Tings", title: "That's Not My Name", year: 2007 },
  { artist: "Popsicle", title: "Not Forever", year: 1996 },
  { artist: "Hello Saferide", title: "The Quiz", year: 2006 },
  { artist: "Ace of Base", title: "All That She Wants", year: 1993 },
  { artist: "Takida", title: "You Learn", year: 2011 },
  { artist: "Seinabo Sey", title: "Younger", year: 2015 },
  { artist: "White Town", title: "Your Woman", year: 1997 },
  { artist: "The Cardigans", title: "Erase / Rewind", year: 1998 },
  { artist: "Galantis", title: "Runaway (U & I)", year: 2015 },
  { artist: "Hanna Ferm", title: "För Evigt", year: 2021 },
  { artist: "Taylor Swift", title: "Anti-Hero", year: 2022 },
  { artist: "Mr. President", title: "Coco Jamboo", year: 1996 },
  { artist: "Nancy Sinatra", title: "Bang Bang (My Baby Shot Me Down)", year: 1966 },
  { artist: "Basic Element", title: "The Promise Man", year: 1994 },
  { artist: "Passenger", title: "Let Her Go", year: 2012 },
  { artist: "Thomas Stenström", title: "Slå mig hårt i ansiktet", year: 2014 },
  { artist: "Deep Blue Something", title: "Breakfast At Tiffany's", year: 1993 },
  { artist: "ABBA", title: "Take A Chance On Me", year: 1977 },
  { artist: "Dr. Alban", title: "It's My Life", year: 1992 },
  { artist: "José González", title: "Heartbeats", year: 2003 },
  { artist: "The Hives", title: "Hate To Say I Told You So", year: 2000 },
  { artist: "Caesars", title: "Jerk It Out", year: 2002 },
  { artist: "Eskobar;Heather Nova", title: "Someone New", year: 2002 },
  { artist: "Tom Paxton", title: "I Give You the Morning", year: 1969 },
  { artist: "Peter LeMarc", title: "Tess", year: 1995 },
  { artist: "KISS", title: "I Was Made For Lovin' You", year: 1979 },
  { artist: "Infinite Mass", title: "Bullet", year: 2001 },
  { artist: "John Waite", title: "Missing You", year: 1984 },
  { artist: "Alesso;Tove Lo", title: "Heroes (we could be)", year: 2015 },
  { artist: "Leila K", title: "Electric", year: 1996 },
  { artist: "Destiny's Child", title: "Survivor", year: 2001 },
  { artist: "Atomic Swing", title: "Stone Me Into The Groove", year: 1993 },
  { artist: "Jumper", title: "När hela världen står utanför", year: 1996 },
  { artist: "Dada Life", title: "Kick Out The Epic Motherf**ker", year: 2012 },
  { artist: "Antiloop", title: "Believe", year: 2002 },
  { artist: "The Platters", title: "Only You (And You Alone)", year: 1986 },
  { artist: "Little Richard", title: "Tutti Frutti", year: 1957 },
  { artist: "Del Shannon", title: "Runaway", year: 1961 },
  { artist: "Chubby Checker", title: "Let's Twist Again", year: 1961 },
  { artist: "Neil Sedaka", title: "Breaking Up Is Hard to Do", year: 1960 },
  { artist: "The Righteous Brothers", title: "Unchained Melody", year: 1965 },
  { artist: "The Rolling Stones", title: "(I Can't Get No) Satisfaction - Mono", year: 1965 },
  { artist: "Queen", title: "Bohemian Rhapsody", year: 2018 },
  { artist: "Survivor", title: "Eye of the Tiger", year: 1982 },
  { artist: "Whitesnake", title: "Here I Go Again", year: 1994 },
  { artist: "Tears For Fears", title: "Everybody Wants To Rule The World", year: 1985 },
  { artist: "Genesis", title: "Invisible Touch", year: 1999 },
  { artist: "Technotronic", title: "Pump Up The Jam", year: 1989 },
  { artist: "C & C Music Factory;Freedom Williams", title: "Gonna Make You Sweat (Everybody Dance Now) (feat. Freedom Williams)", year: 2000 },
  { artist: "Cypress Hill", title: "Insane in the Brain", year: 1993 },
  { artist: "James", title: "Laid", year: 1993 },
  { artist: "Pulp", title: "Common People - Full Length Version", year: 1995 },
  { artist: "Ebba Grön", title: "800°", year: 1981 },
  { artist: "The Corrs;Tin Tin Out", title: "What Can I Do", year: 1998 },
  { artist: "Tomas Ledin", title: "En del av mitt hjärta", year: 1990 },
  { artist: "Moby", title: "Porcelain", year: 1999 },
  { artist: "Keith Urban", title: "Somebody Like You", year: 2002 },
  { artist: "The Darkness", title: "I Believe in a Thing Called Love", year: 2003 },
  { artist: "Amy Macdonald", title: "This Is The Life", year: 2007 },
  { artist: "Hozier", title: "Take Me To Church", year: 2014 },
  { artist: "Fifth Harmony;Kid Ink", title: "Worth It (feat. Kid Ink)", year: 2015 },
  { artist: "Zedd;Maren Morris;Grey", title: "The Middle", year: 2018 },
  { artist: "Sabina Ddumba", title: "Effortless", year: 2016 },
  { artist: "Ariana Grande", title: "no tears left to cry", year: 2018 },
  { artist: "First Aid Kit", title: "My Silver Lining", year: 2014 },
  { artist: "Simple Minds", title: "Don't You (Forget About Me)", year: 1985 },
  { artist: "The Pussycat Dolls;Busta Rhymes", title: "Don't Cha", year: 2005 },
  { artist: "Gwen Stefani", title: "Hollaback Girl", year: 2004 },
  { artist: "Sugababes", title: "Push The Button", year: 2005 },
  { artist: "Daniel Adams-Ray", title: "Gubben i lådan", year: 2010 },
  { artist: "Etta James", title: "At Last", year: 1960 },
  { artist: "Evert Taube", title: "Sjösala vals", year: 2003 },
  { artist: "Bob Dylan", title: "Knockin' On Heaven's Door", year: 1973 },
  { artist: "John Denver", title: "Take Me Home, Country Roads - Original Version", year: 1971 },
  { artist: "The Calling", title: "Wherever You Will Go", year: 2001 },
  { artist: "Juanes", title: "La Camisa Negra", year: 2004 },
  { artist: "SNAP!", title: "Rhythm Is A Dancer", year: 1992 },
  { artist: "Daryl Hall & John Oates", title: "Out of Touch", year: 2009 },
  { artist: "Radiohead", title: "Creep", year: 1993 },
  { artist: "Maroon 5", title: "This Love", year: 2002 },
  { artist: "Ja Rule;Ashanti", title: "Always On Time", year: 2001 },
  { artist: "New World", title: "Living Next Door to Alice", year: 2020 },
  { artist: "Diddy;Faith Evans;112", title: "I'll Be Missing You (feat. Faith Evans, 112)", year: 2004 },
  { artist: "Baby Bash;Frankie J", title: "Suga Suga", year: 2003 },
  { artist: "Savage Garden", title: "To the Moon & Back", year: 1997 },
  { artist: "Mats Ronander;Kim Larsen", title: "Gör mig lycklig nu", year: 1992 },
  { artist: "Wiz Khalifa;Charlie Puth", title: "See You Again (feat. Charlie Puth)", year: 2015 },
  { artist: "Shaggy;Rik Rok", title: "It Wasn't Me", year: 2000 },
  { artist: "Enrico Caruso", title: "O Sole Mio", year: 2011 },
  { artist: "Marvin Gaye;Tammi Terrell", title: "Ain't No Mountain High Enough", year: 2000 },
  { artist: "Oh Laura", title: "Release Me", year: 2007 },
  { artist: "Måns Zelmerlöw", title: "Heroes", year: 2015 },
  { artist: "Al Green", title: "Let's Stay Together", year: 1972 },
  { artist: "The Staple Singers", title: "I'll Take You There", year: 2007 },
  { artist: "Otis Redding", title: "(Sittin' On) the Dock of the Bay", year: 1968 },
  { artist: "Frankie Valli & The Four Seasons", title: "Sherry", year: 2003 },
  { artist: "The Tokens", title: "The Lion Sleeps Tonight", year: 1970 },
  { artist: "The Supremes", title: "Baby Love", year: 1964 },
  { artist: "Martha Reeves & The Vandellas", title: "(Love Is Like A) Heat Wave", year: 1963 },
  { artist: "Paramount Jubilee Singers", title: "When All The Saints Come Marching In (Take 2)", year: 2005 },
  { artist: "Bee Gees", title: "Stayin Alive", year: 2020 },
  { artist: "Tove Lo", title: "No One Dies From Love", year: 2022 },
  { artist: "Mange Schmidt", title: "Giftig", year: 2007 },
  { artist: "Louis Armstrong", title: "What A Wonderful World", year: 1968 },
  { artist: "Run–D.M.C.;Aerosmith", title: "Walk This Way (feat. Aerosmith)", year: 1986 },
  { artist: "Mr. Big", title: "To Be With You - 2021 Remastered", year: 1991 },
  { artist: "American Authors", title: "Best Day Of My Life", year: 2014 },
  { artist: "The Buggles", title: "Video Killed The Radio Star - Single Version", year: 2009 },
  { artist: "Frank Sinatra;Count Basie", title: "Fly Me To The Moon - 2008 Remastered", year: 2008 },
  { artist: "Eric Clapton", title: "I Shot The Sheriff", year: 1974 },
  { artist: "Neil Young", title: "Heart Of Gold", year: 2010 },
  { artist: "MAGIC!", title: "Rude", year: 2014 },
  { artist: "Matchbox Twenty", title: "3AM", year: 1996 },
  { artist: "Jessica Folcker", title: "How Will I Know (Who You Are)", year: 1998 },
  { artist: "Train", title: "Drops of Jupiter (Tell Me)", year: 2001 },
  { artist: "Vanessa Amorosi", title: "Absolutely Everybody", year: 2000 },
  { artist: "Los Del Rio", title: "Macarena", year: 2002 },
  { artist: "Peps Persson", title: "Oh boy", year: 2004 },
  { artist: "Snook", title: "Mister Cool", year: 2004 },
  { artist: "Five", title: "Everybody Get Up - Radio Edit", year: 2001 },
  { artist: "iNi Kamoze", title: "Here Comes the Hotstepper", year: 2001 },
  { artist: "Inner Circle", title: "Sweat (A La La La La Long)", year: 2010 },
  { artist: "Coolio;L.V.", title: "Gangsta's Paradise", year: 1995 },
  { artist: "Bloodhound Gang", title: "Fire Water Burn", year: 1996 },
  { artist: "Belinda Carlisle", title: "Heaven Is A Place On Earth", year: 1987 },
  { artist: "UB40", title: "Red Red Wine", year: 2000 },
  { artist: "Depeche Mode", title: "Just Can't Get Enough", year: 1981 },
  { artist: "Van Morrison", title: "Brown Eyed Girl", year: 1967 },
  { artist: "Tina Charles", title: "I Love to Love", year: 1997 },
  { artist: "Bill Withers", title: "Ain't No Sunshine", year: 1971 },
  { artist: "Barry Manilow", title: "Mandy", year: 1974 },
  { artist: "Lambretta", title: "Creep", year: 2001 },
  { artist: "Jess Glynne", title: "Hold My Hand", year: 2015 },
  { artist: "The Lumineers", title: "Ho Hey", year: 2012 },
  { artist: "Klingande", title: "Jubel - Radio Edit", year: 2013 },
  { artist: "CeeLo Green", title: "Fuck You", year: 2010 },
  { artist: "Ella Henderson", title: "Ghost", year: 2014 },
  { artist: "Simon & Garfunkel", title: "Mrs. Robinson", year: 2001 },
  { artist: "Harry Nilsson", title: "Everybody's Talkin'", year: 1969 },
  { artist: "Jennifer Rush", title: "The Power of Love", year: 1995 },
  { artist: "Olly Alexander (Years & Years)", title: "King", year: 2015 },
  { artist: "Mauro Scocco", title: "Sarah", year: 1988 },
  { artist: "Alice Deejay", title: "Better Off Alone", year: 2000 },
  { artist: "Kikki Danielsson", title: "Bra vibrationer", year: 1985 },
  { artist: "The Troggs", title: "Wild Thing", year: 1966 },
  { artist: "Chris Montez", title: "Let's Dance", year: 1962 },
  { artist: "September", title: "Cry for You", year: 2007 },
  { artist: "Patrick Swayze;Wendy Fraser", title: "She's Like the Wind (feat. Wendy Fraser)", year: 2012 },
  { artist: "Jerry Williams", title: "I Can Jive", year: 1979 },
  { artist: "Dionne Warwick", title: "Heartbreaker", year: 1982 },
  { artist: "Barbra Streisand", title: "Woman in Love", year: 1980 },
  { artist: "Panetoz", title: "Dansa Pausa", year: 2012 },
  { artist: "Duck Sauce", title: "Barbra Streisand - Radio Edit", year: 2010 },
  { artist: "Led Zeppelin", title: "Stairway to Heaven - Remaster", year: 1971 },
  { artist: "Pink Floyd", title: "Another Brick In The Wall, Pt. 2 - 2011 Remastered Version", year: 1979 },
  { artist: "Stefan Rüdén", title: "Sofia dansar go-go", year: 2003 },
  { artist: "AC/DC", title: "Thunderstruck", year: 1990 },
  { artist: "Bon Jovi", title: "Livin' On A Prayer", year: 1986 },
  { artist: "Santana;The Product G&B", title: "Maria Maria (feat. The Product G&B)", year: 1999 },
  { artist: "Harry Belafonte", title: "Banana Boat (Day-O)", year: 1956 },
  { artist: "Kris Kross", title: "Jump", year: 1992 },
  { artist: "Pet Shop Boys", title: "Go West - 2003 Remaster", year: 2003 },
  { artist: "Spandau Ballet", title: "True", year: 1986 },
  { artist: "Alice Cooper", title: "Poison", year: 1989 },
  { artist: "Martin Stenmarck", title: "Sjumilakliv", year: 2006 },
  { artist: "The Dubliners", title: "Whiskey in the Jar", year: 2002 },
  { artist: "Céline Dion", title: "Because You Loved Me", year: 2019 },
  { artist: "Pretenders", title: "I'll Stand by You", year: 1994 },
  { artist: "Ava Max", title: "Sweet but Psycho", year: 2020 },
  { artist: "Dean Lewis", title: "Be Alright", year: 2018 },
  { artist: "Gym Class Heroes;Adam Levine", title: "Stereo Hearts (feat. Adam Levine)", year: 2011 },
  { artist: "David Guetta;Kelly Rowland", title: "When Love Takes Over (feat. Kelly Rowland)", year: 2010 },
  { artist: "Cornershop", title: "Brimful of Asha", year: 1997 },
  { artist: "Jason Mraz", title: "I'm Yours", year: 2008 },
  { artist: "Linda Lyndell", title: "What A Man", year: 1993 },
  { artist: "Charles Wright & The Watts 103rd Street Rhythm Band", title: "Express Yourself", year: 1970 },
  { artist: "Nic & The Family", title: "Hej Monica", year: 2004 },
  { artist: "Ne-Yo", title: "So Sick", year: 2006 },
  { artist: "Neneh Cherry", title: "Woman", year: 1996 },
  { artist: "Snoop Dogg;Pharrell Williams", title: "Drop It Like It's Hot", year: 2004 },
  { artist: "Foster The People", title: "Pumped Up Kicks", year: 2011 },
  { artist: "Missy Elliott", title: "Get Ur Freak On", year: 2001 },
  { artist: "USHER;Lil Jon;Ludacris", title: "Yeah! (feat. Lil Jon & Ludacris)", year: 2004 },
  { artist: "Dexys Midnight Runners", title: "Come On Eileen", year: 1982 },
  { artist: "Maggie Lindemann", title: "Pretty Girl", year: 2016 },
  { artist: "Colbie Caillat", title: "Bubbly", year: 2007 },
  { artist: "Paul Young", title: "Every Time You Go Away - Radio Edit", year: 1991 },
  { artist: "Capital Cities", title: "Safe And Sound", year: 2013 },
  { artist: "Peter Bjorn and John", title: "Young Folks", year: 2006 },
  { artist: "Fall Out Boy", title: "Centuries", year: 2015 },
  { artist: "Panic! At The Disco", title: "High Hopes", year: 2018 },
  { artist: "Martika", title: "Toy Soldiers", year: 1988 },
  { artist: "Édith Piaf", title: "Non, je ne regrette rien", year: 1987 },
  { artist: "Dinah Washington", title: "What a Difference a Day Makes", year: 2011 },
  { artist: "Flo Rida", title: "Good Feeling", year: 2012 },
  { artist: "Bryan Adams", title: "Summer Of '69", year: 1984 },
  { artist: "The Beatles", title: "Don't Let Me Down - Remastered 2009", year: 1973 },
  { artist: "Ed Sheeran", title: "Bad Habits", year: 2021 },
  { artist: "Elton John;Dua Lipa;PNAU", title: "Cold Heart - PNAU Remix", year: 2021 },
  { artist: "Harry Styles", title: "As It Was", year: 2022 },
  { artist: "Kate Bush", title: "Running Up That Hill (A Deal With God)", year: 1985 },
  { artist: "Jack Harlow", title: "First Class", year: 2022 },
  { artist: "Post Malone;21 Savage", title: "rockstar (feat. 21 Savage)", year: 2018 },
  { artist: "Janis Joplin", title: "Mercedes Benz", year: 1971 },
  { artist: "Magnus Uggla", title: "Kung för en dag", year: 1977 },
  { artist: "O-Zone", title: "Dragostea din tei", year: 2004 },
  { artist: "Anastacia", title: "I'm Outta Love", year: 2000 },
  { artist: "Joan Osborne", title: "One Of Us", year: 1995 },
  { artist: "Kim Wilde", title: "Kids In America", year: 1981 },
  { artist: "All Saints", title: "Pure Shores", year: 2000 },
  { artist: "Nickelback", title: "Rockstar", year: 2005 },
  { artist: "Roxette", title: "Dressed For Success", year: 1988 },
  { artist: "Robyn", title: "Hang with Me", year: 2010 },
  { artist: "Bobby McFerrin", title: "Don't Worry Be Happy", year: 1997 },
  { artist: "LMFAO;Lauren Bennett;GoonRock", title: "Party Rock Anthem", year: 2010 },
  { artist: "The Bangles;Susanna Hoffs", title: "Eternal Flame", year: 2004 },
  { artist: "Fatboy Slim", title: "The Rockafeller Skank", year: 1998 },
  { artist: "Sam Smith", title: "Stay With Me", year: 2014 },
  { artist: "Junior Senior", title: "Move Your Feet", year: 2002 },
  { artist: "Milow", title: "Ayo Technology", year: 2012 },
  { artist: "Major Lazer;MØ;DJ Snake", title: "Lean On (feat. MØ & DJ Snake)", year: 2015 },
  { artist: "Powfu;beabadoobee", title: "death bed (coffee for your head)", year: 2020 },
  { artist: "2Pac;Roger;Dr. Dre", title: "California Love - Original Version", year: 1998 },
  { artist: "Per Myrberg", title: "Trettifyran", year: 1965 },
  { artist: "Europe", title: "The Final Countdown", year: 1986 },
  { artist: "Midnight Oil", title: "Beds Are Burning - Remastered", year: 1987 },
  { artist: "U2", title: "With Or Without You", year: 2006 },
  { artist: "The Ark", title: "Calleth You, Cometh I", year: 2002 },
  { artist: "Sam Feldt;RANI", title: "Post Malone (feat. RANI)", year: 2019 },
  { artist: "Staffan Hellstrand", title: "Lilla fågel blå", year: 1993 },
  { artist: "X Ambassadors", title: "Renegades", year: 2015 },
  { artist: "Avicii", title: "Wake Me Up", year: 2013 },
  { artist: "Gina G;Motiv8", title: "Ooh Aah...Just a Little Bit - Motiv8 Radio Edit", year: 1997 },
  { artist: "Benny Goodman", title: "Sing, Sing, Sing", year: 2007 },
  { artist: "Eva Dahlgren", title: "Vem tänder stjärnorna", year: 1991 },
  { artist: "Jerry Lee Lewis", title: "Great Balls of Fire", year: 2013 },
  { artist: "Allan Sherman", title: "Hello Muddah Hello Fadduh (A Letter from Camp Granada)", year: 2017 },
  { artist: "Rednex", title: "Cotton Eye Joe", year: 1994 }
];